export const GET_SONG_DETAILS = 'get_song_details'
export const GET_LRC = 'get_lrc'
export const COMPUTED_LRC = 'computed_lrc'
export const ADD_TO_MY_LIST = 'add_to_my_list'
export const REMOVE_FROM_MY_LIST = 'remove_from_my_list'

export const OPEN_MUSIC_LIST = 'open_music_list'
export const CLOSE_MUSIC_LIST = 'close_music_list'
export const SWITCH_MUSIC_PLAYER = 'switch_music_player'
export const CHANGE_PLAYER_MUSIC = 'change_player_music'
export const SET_PLAYER_PROGRESS = 'set_player_progress'
export const CHANGE_MUSIC_ORDER = 'change_music_order'
